(defun sublime-text-2 ()
  (interactive)
  (color-theme-install
   '(sublime-text-2
     ((background-color . "#171717")
      (background-mode . light)
      (border-color . "#1a1a1a")
      (cursor-color . "#fce94f")
      (foreground-color . "#cfbfad")
      (mouse-color . "black"))
     (diff-file-header ((t (:bold t :background "#102426"))))
     (diff-hunk-header ((t (:bold t :background "#102426"))))
     (secondary-selection ((t (:background "#102022"))))
     (fringe ((t (:background "#171717"))))
     (mode-line ((t (:background "#202020" :foreground "grey70"))))
     (mode-line-inactive ((t (:inherit mode-line :background "#202020" :foreground "grey60"))))
     (region ((t (:foreground "#404040" :background "#CC9900"))))
     (font-lock-builtin-face ((t (:foreground "#52e3f6"))))
     (font-lock-comment-face ((t (:foreground "#ffffff"))))
     (font-lock-function-name-face ((t (:foreground "#edd400"))))
     (font-lock-keyword-face ((t (:foreground "#ff007f"))))
     (font-lock-string-face ((t (:foreground "#ece47e"))))
     (font-lock-type-face ((t (:foreground"#8ae234"))))
     (font-lock-variable-name-face ((t (:foreground "#8ae234"))))
     (minibuffer-prompt ((t (:foreground "#729fcf" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     (tabbar-button ((t (:inherit tabbar-default :background "#202020" :foreground "white" :inverse-video nil))))
     (tabbar-button-highlight ((t (:inherit tabbar-default :box nil))))
     (tabbar-default ((t (:inherit default :height 0.9))))
     (tabbar-selected ((t (:inherit tabbar-default :foreground "yellow" :inverse-video nil))))
     (tabbar-separator ((t (:background "#171717" :inverse-video nil))))
     (tabbar-unselected ((t (:inherit tabbar-default :inverse-video nil))))
     )))
(provide 'sublime-text-2)
